[versions]
agp = "8.11.0"
appcompat = "1.7.1"
appintro = "6.3.1"
balloon = "1.7.0"
constraintlayout = "2.2.1"
coreSplashscreen = "1.2.0"
kotlin = "2.2.0"
kotlinxSerializationJson = "1.9.0"
legacySupportV4 = "1.0.0"
lifecycleExtensions = "2.2.0"
material = "1.13.0"
preferenceKtx = "1.2.1"
recyclerview = "1.4.0"
room = "2.8.4"
timber = "5.0.1"
treessence = "1.1.2"
workRuntimeKtx = "2.11.0"
ksp = "2.2.20-2.0.3"

[libraries]
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacySupportV4" }
androidx-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycleExtensions" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-common = { module = "androidx.room:room-common", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
appintro = { module = "com.github.AppIntro:AppIntro", version.ref = "appintro" }
balloon = { module = "com.github.skydoves:balloon", version.ref = "balloon" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
material = { module = "com.google.android.material:material", version.ref = "material" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
treessence = { module = "com.github.bastienpaulfr:Treessence", version.ref = "treessence" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinxSerializable = { id = 'org.jetbrains.kotlin.plugin.serialization', version.ref = "kotlin"}
ksp = { id = 'com.google.devtools.ksp', version.ref = "ksp"}